complexity:
  LongParameterList:
    functionThreshold: 15 # default 6
    constructorThreshold: 15 # default 7

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  ThrowsCount:
    max: 6
