version: '3.8'

services:
  web:
    container_name: "echo_backend_web"
    restart: 'always'
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/app/:z
    ports:
    - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: "echo_backend_db"
    image: postgres:12.0
    restart: 'always'
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
