version: "3.7"

services:
  db:
    container_name: "echo_backend_test_db"
    image: postgres:13.0
    ports:
      - 32782:5432
    environment:
      - POSTGRES_DB=echokarriere
      - POSTGRES_USER=karriere
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
