version: "3.7"

services:
  web:
    container_name: "echo_backend_web"
    restart: unless-stopped
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/:z
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: "echo_backend_db"
    image: postgres:12.0
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - postgres
    env_file: .env

    pgadmin:
      container_name: "echo_backend_pgadmin"
      image: dpage/pgadmin4:4
      restart: unless-stopped
      volumes:
        - pgadmin_data:/root/.pgadmin
      ports:
        - 5000:80
      networks:
        - postgres
      env_file: .env

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
