version: "3.7"

services:
  test_db:
    container_name: "echo_backend_test_db"
    image: postgres:11.6
    ports:
      - 32789:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: karriere
      POSTGRES_PASSWORD: password
