# Generated by Django 3.0.6 on 2020-05-31 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSchema",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact_person", models.CharField(help_text="Name of person who contacted us", max_length=255)),
                ("contact_email", models.EmailField(help_text="Email of person who contacted us", max_length=255)),
                ("message", models.TextField(help_text="Message from user")),
                ("date_submitted", models.DateTimeField(auto_now_add=True, help_text="Date message was sent")),
                (
                    "answered",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Whether we have answered the person back (will be automatically updated when saving)",
                    ),
                ),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Who replied",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Contact Form", "verbose_name_plural": "Contact Form",},
        ),
    ]
