# Generated by Django 3.0.7 on 2020-06-15 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactschema",
            name="answered_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Who replied",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
