/*
 * This file is generated by jOOQ.
 */
package no.echokarriere.db.enums;


import no.echokarriere.db.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Usertype implements EnumType {

    ADMIN("ADMIN"),

    STAFF("STAFF"),

    USER("USER");

    private final String literal;

    private Usertype(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "usertype";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
