graphql:
  packages: "no.echokarriere.backend"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/echokarriere
    username: karriere
    password: password
    driver-class-name: org.postgresql.Driver
