# Generated by Django 3.0.7 on 2020-06-15 18:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of event", max_length=120)),
                (
                    "active",
                    models.BooleanField(
                        help_text="Whether the event is 'active', e.g. the current event", verbose_name="Active"
                    ),
                ),
                ("year", models.DateField(help_text="Year during which the event happens")),
            ],
        ),
        migrations.CreateModel(
            name="EventDate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title for date, e.g. 'Dag 1'", max_length=120)),
                ("start", models.DateTimeField(help_text="Date and time the event starts for a given day")),
                ("end", models.DateTimeField(help_text="Date and time the event ends for a given day")),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event to link dates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        related_query_name="dates",
                        to="event.Event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventContent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title for content block", max_length=120)),
                (
                    "title_id",
                    models.CharField(
                        editable=False, help_text="Automatically generated field, used by frontend", max_length=120
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(help_text="Content for block")),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Event to link content to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        related_query_name="content",
                        to="event.Event",
                    ),
                ),
            ],
        ),
    ]
