# Generated by Django 3.0.6 on 2020-05-20 21:11
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("name", models.CharField(max_length=120)),
                ("active", models.BooleanField()),
                ("year", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="EventDate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="event.Event"),),
            ],
        ),
        migrations.CreateModel(
            name="EventContent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("title", models.CharField(max_length=120)),
                ("title_id", models.CharField(max_length=120)),
                ("content", ckeditor.fields.RichTextField()),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="event.Event"),),
            ],
        ),
    ]
