# Generated by Django 3.0.6 on 2020-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_auto_20200530_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdate",
            name="title",
            field=models.CharField(default="", max_length=120),
            preserve_default=False,
        ),
    ]
