/*
 * This file is generated by jOOQ.
 */
package no.echokarriere.db;


import no.echokarriere.db.tables.Category;
import no.echokarriere.db.tables.Company;
import no.echokarriere.db.tables.FlywaySchemaHistory;
import no.echokarriere.db.tables.records.CategoryRecord;
import no.echokarriere.db.tables.records.CompanyRecord;
import no.echokarriere.db.tables.records.FlywaySchemaHistoryRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoryRecord> CATEGORY_PKEY = Internal.createUniqueKey(Category.CATEGORY, DSL.name("category_pkey"), new TableField[] { Category.CATEGORY.ID }, true);
    public static final UniqueKey<CategoryRecord> CATEGORY_SLUG_KEY = Internal.createUniqueKey(Category.CATEGORY, DSL.name("category_slug_key"), new TableField[] { Category.CATEGORY.SLUG }, true);
    public static final UniqueKey<CategoryRecord> CATEGORY_TITLE_KEY = Internal.createUniqueKey(Category.CATEGORY, DSL.name("category_title_key"), new TableField[] { Category.CATEGORY.TITLE }, true);
    public static final UniqueKey<CompanyRecord> COMPANY_NAME_KEY = Internal.createUniqueKey(Company.COMPANY, DSL.name("company_name_key"), new TableField[] { Company.COMPANY.NAME }, true);
    public static final UniqueKey<CompanyRecord> COMPANY_PKEY = Internal.createUniqueKey(Company.COMPANY, DSL.name("company_pkey"), new TableField[] { Company.COMPANY.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
}
