/*
 * This file is generated by jOOQ.
 */
package no.echokarriere.db;


import no.echokarriere.db.tables.PgpArmorHeaders;
import no.echokarriere.db.tables.records.PgpArmorHeadersRecord;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> pgpArmorHeaders(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(no.echokarriere.db.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders pgpArmorHeaders(
          String __1
    ) {
        return no.echokarriere.db.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders pgpArmorHeaders(
          Field<String> __1
    ) {
        return no.echokarriere.db.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        );
    }
}
