# Generated by Django 3.0.7 on 2020-06-15 18:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("namespace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True)),
                ("content", ckeditor.fields.RichTextField()),
                ("slug", models.SlugField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Published"), ("D", "Draft"), ("X", "Deleted")], default="D", max_length=1
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("published_on", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "namespace",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="namespace.Namespace"
                    ),
                ),
            ],
            options={"ordering": ["modified_on"],},
        ),
    ]
