# Generated by Django 3.0.6 on 2020-05-20 21:11

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=250)),
                ("namespace", models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("title", models.CharField(max_length=100, unique=True)),
                ("content", ckeditor.fields.RichTextField()),
                ("slug", models.SlugField(editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Published"), ("D", "Draft"), ("X", "Deleted")], default="D", max_length=1,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("published_on", models.DateTimeField(editable=False)),
                (
                    "namespace",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.Namespace",
                    ),
                ),
            ],
            options={"ordering": ["modified_on"],},
        ),
    ]
