/*
 * This file is generated by jOOQ.
 */
package no.echokarriere.db.tables.records;


import no.echokarriere.db.tables.FormSubmission;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FormSubmissionRecord extends UpdatableRecordImpl<FormSubmissionRecord> implements Record5<UUID, UUID, JSONB, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.form_submission.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.form_submission.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.form_submission.form</code>.
     */
    public void setForm(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.form_submission.form</code>.
     */
    public UUID getForm() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.form_submission.data</code>.
     */
    public void setData(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.form_submission.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.form_submission.submitted_at</code>.
     */
    public void setSubmittedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.form_submission.submitted_at</code>.
     */
    public OffsetDateTime getSubmittedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.form_submission.modified_at</code>.
     */
    public void setModifiedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.form_submission.modified_at</code>.
     */
    public OffsetDateTime getModifiedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, JSONB, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, UUID, JSONB, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return FormSubmission.FORM_SUBMISSION.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FormSubmission.FORM_SUBMISSION.FORM;
    }

    @Override
    public Field<JSONB> field3() {
        return FormSubmission.FORM_SUBMISSION.DATA;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FormSubmission.FORM_SUBMISSION.SUBMITTED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return FormSubmission.FORM_SUBMISSION.MODIFIED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getForm();
    }

    @Override
    public JSONB component3() {
        return getData();
    }

    @Override
    public OffsetDateTime component4() {
        return getSubmittedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getModifiedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getForm();
    }

    @Override
    public JSONB value3() {
        return getData();
    }

    @Override
    public OffsetDateTime value4() {
        return getSubmittedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getModifiedAt();
    }

    @Override
    public FormSubmissionRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public FormSubmissionRecord value2(UUID value) {
        setForm(value);
        return this;
    }

    @Override
    public FormSubmissionRecord value3(JSONB value) {
        setData(value);
        return this;
    }

    @Override
    public FormSubmissionRecord value4(OffsetDateTime value) {
        setSubmittedAt(value);
        return this;
    }

    @Override
    public FormSubmissionRecord value5(OffsetDateTime value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public FormSubmissionRecord values(UUID value1, UUID value2, JSONB value3, OffsetDateTime value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FormSubmissionRecord
     */
    public FormSubmissionRecord() {
        super(FormSubmission.FORM_SUBMISSION);
    }

    /**
     * Create a detached, initialised FormSubmissionRecord
     */
    public FormSubmissionRecord(UUID id, UUID form, JSONB data, OffsetDateTime submittedAt, OffsetDateTime modifiedAt) {
        super(FormSubmission.FORM_SUBMISSION);

        setId(id);
        setForm(form);
        setData(data);
        setSubmittedAt(submittedAt);
        setModifiedAt(modifiedAt);
    }
}
