name: Deploy dev

on:
  push:
    branches:
      - bootify
  workflow_dispatch:

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'echo-karriere'
        slot-name: 'dev'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ce79176bdf7947a48f5e78a23d212ac8 }}
        package: '${{ github.workspace }}/target/*.jar'
