name: Deploy dev

on:
  workflow_run:
    workflows:
      - Pipeline
    branches:
      - bootify
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: jdbc:postgresql://localhost:32789/echokarriere

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_DB: echokarriere
          POSTGRES_USER: karriere
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 32789:5432

    steps:
      - uses: actions/checkout@v2

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'echo-karriere'
          slot-name: 'dev'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_ce79176bdf7947a48f5e78a23d212ac8 }}
          package: '${{ github.workspace }}/build/libs/*.jar'
