name: Deploy dev

on:
  push:
    branches:
      - bootify
  workflow_dispatch:

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: karriere
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 32789:5432

    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'echo-karriere'
          slot-name: 'dev'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_ce79176bdf7947a48f5e78a23d212ac8 }}
          package: '${{ github.workspace }}/target/*.jar'
