# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - echokarriere(dev)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://karriere:password@localhost:32789/test_db?schem

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: karriere
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 32789:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install and build
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: |
          npm run format:check
          npm run lint:check

      - name: Test
        run: |
          npm run test
          npm run test:e2e
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_NAME: ${{ secrets.AZURE_TENANT_NAME }}
          AZURE_POLICY_NAME: ${{ secrets.AZURE_POLICY_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "dev"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Migrate dev database
        run: npx prisma migrate reset --force --skip-generate
        env:
          DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}

      - name: Package repo
        run: |
          npm ci --production --ignore-scripts
          zip app.zip -r * -q

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "echokarriere"
          slot-name: "dev"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_339790a1cc8d4dea8df5d9708352ee81 }}
          package: app.zip
