name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DATABASE_URL: jdbc:postgresql://localhost:32789/test_db

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: karriere
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 32789:5432

    steps:
      - uses: actions/checkout@v2

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: /root/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check
        run: ./gradlew check --info

      - name: Build
        run: ./gradlew build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: '${{ github.workspace }}/build/libs/*.jar'

      - name: SonarQube analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [ tests ]
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'echokarriere'
          slot-name: 'dev'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6732f46e467045c59d6c94cd23483738 }}
          package: '*.jar'
